(function () {
  'use strict';
  const translations = {
      es: {
        nav_disciplines: 'Disciplinas',
        nav_projects:    'Proyectos',
        nav_about:       'Sobre mí',
        nav_portfolios:  'Portafolios',
        nav_cta:         'Conectemos',
        hero_badge:      'Product Design',
        hero_greeting:   'Hola, soy',
        hero_intro:      'Aquí podrás encontrar <strong>mis trabajos y proyectos</strong> en distintas disciplinas.',
        hero_cta_primary:   'Ver proyectos',
        hero_cta_secondary: 'Contactar',
        hero_scroll:     'Scroll para explorar',
        disc_label: 'Lo que hago',
        disc_title: 'Disciplinas',
        disc_sub:   'Áreas en las que trabajo y sigo explorando.',
        disc_all:   'Todos',
        proj_label: 'Mi trabajo',
        proj_title: 'Proyectos',
        proj_sub:   'Casos seleccionados agrupados por disciplina.',
        about_label: 'Sobre mí',
        about_title: 'CONÓCEME',
        about_p1:    'Haber crecido en una <strong>constante mudanza</strong>, me abrió los ojos sobre las diferentes realidades de mi país, y la propia realidad individual que supone cada persona.',
        about_p2:    'Pero a la par, crecí como un empedernido explorador de <strong>la realidad digital</strong> que nos une. Estas vivencias generaron en mí una inmensa curiosidad sobre la relación entre las personas y la tecnología.',
        about_p3:    'Con los años, comprendí que mi propósito debía centrarse en <strong>mejorar la experiencia</strong> que vivimos en esta convergencia de realidades.',
        about_p4:    'Soy Israel, estas son mis primeras incursiones en el mundo del Product Design. Actualmente, estudio <strong>Comunicaciones en la Universidad de Lima</strong>, y siempre, SIEMPRE, estoy dispuesto a aprender algo nuevo.',
        stat_projects:    'Proyectos realizados',
        stat_disciplines: 'Disciplinas',
        stat_years:       'Años de proyectos',
        stat_learning:    'Ganas de aprender',
        about_quote:  '"Mi propósito se centra en mejorar la experiencia que vivimos en la <strong>convergencia entre el mundo digital y humano</strong>."',
        info_studies:  'Estudios',
        info_degree:   'Carrera',
        info_location: 'Ubicación',
        info_focus:    'Enfoque',
        port_label: 'Más trabajo',
        port_title: 'Más Portafolios',
        port_sub:   'Explora portafolios adicionales por disciplina.',
        port1_title: 'Product Design e Innovación',
        port1_desc:  'Portafolio completo de proyectos de diseño de producto e innovación. Casos de estudio, procesos y resultados.',
        port2_title: 'Diseño Visual',
        port2_desc:  'Colección de trabajos de diseño visual: identidades, composiciones gráficas y piezas visuales.',
        contact_label: 'Hablemos',
        contact_title: 'CONECTEMOS!',
        contact_p1:    '¿Tienes un proyecto en mente? ¿Quieres colaborar o simplemente conocernos?',
        contact_p2:    'Siempre estoy abierto a nuevas oportunidades, conversaciones interesantes y desafíos creativos.',
        contact_p3:    'No dudes en escribirme — respondiendo siempre. 🚀',
        contact_wa_sub:   'Escríbeme directo',
        contact_li_sub:   'Conectemos profesionalmente',
        contact_mail_sub: 'Envíame un correo',
        footer_home:    'Inicio',
        footer_contact: 'Contacto',
        footer_made:    'Hecho con ❤️ y mucha curiosidad',
      },
      en: {
        nav_disciplines: 'Disciplines',
        nav_projects:    'Projects',
        nav_about:       'About me',
        nav_portfolios:  'Portfolios',
        nav_cta:         "Let's connect",
        hero_badge:      'Product Design',
        hero_greeting:   "Hi, I'm",
        hero_intro:      'Here you can find <strong>my work and projects</strong> across different disciplines.',
        hero_cta_primary:   'View projects',
        hero_cta_secondary: 'Contact me',
        hero_scroll:     'Scroll to explore',
        disc_label: 'What I do',
        disc_title: 'Disciplines',
        disc_sub:   'Areas I work in and keep exploring.',
        disc_all:   'All',
        proj_label: 'My work',
        proj_title: 'Projects',
        proj_sub:   'Selected cases grouped by discipline.',
        about_label: 'About me',
        about_title: 'GET TO KNOW ME',
        about_p1:    'Growing up constantly <strong>moving around</strong> opened my eyes to the different realities of my country, and the individual reality that each person carries.',
        about_p2:    'I grew up as an avid explorer of <strong>the digital reality</strong> that connects us. These experiences sparked in me a deep curiosity about the relationship between people and technology.',
        about_p3:    'Over the years, I understood that my purpose should focus on <strong>improving the experience</strong> we live in this convergence of realities.',
        about_p4:    'I am Israel, and these are my first explorations in Product Design. I currently study <strong>Communications at Universidad de Lima</strong>, and I am always, ALWAYS, willing to learn something new.',
        stat_projects:    'Completed projects',
        stat_disciplines: 'Disciplines',
        stat_years:       'Years of projects',
        stat_learning:    'Eagerness to learn',
        about_quote:  '"My purpose is to improve the experience we live in the <strong>convergence between the digital and human world</strong>."',
        info_studies:  'Studies',
        info_degree:   'Degree',
        info_location: 'Location',
        info_focus:    'Focus',
        port_label: 'More work',
        port_title: 'More Portfolios',
        port_sub:   'Explore additional portfolios by discipline.',
        port1_title: 'Product Design and Innovation',
        port1_desc:  'Complete portfolio of product design and innovation projects. Case studies, processes and outcomes.',
        port2_title: 'Visual Design',
        port2_desc:  'Collection of visual design work: brand identities, graphic compositions and visual pieces.',
        contact_label: "Let's talk",
        contact_title: "LET'S CONNECT!",
        contact_p1:    'Do you have a project in mind? Want to collaborate or just get to know each other?',
        contact_p2:    'I am always open to new opportunities, interesting conversations and creative challenges.',
        contact_p3:    "Don't hesitate to reach out — I always reply. 🚀",
        contact_wa_sub:   'Message me directly',
        contact_li_sub:   "Let's connect professionally",
        contact_mail_sub: 'Send me an email',
        footer_home:    'Home',
        footer_contact: 'Contact',
        footer_made:    'Made with ❤️ and lots of curiosity',
      }
    };

    
  window.PORTFOLIO_TRANSLATIONS = translations;
})();
